# Generated by Django 6.0.3 on 2026-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('unique_code', models.CharField(max_length=15, unique=True)),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('department', models.CharField(choices=[('5000', '5000'), ('5500', '5500'), ('5800', '5800'), ('6000', '6000')], max_length=4)),
            ],
        ),
    ]
