# Generated by Django 6.0.3 on 2026-04-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_releasedcomponent'),
        ('list_LPT', '0005_rename_lpt_list_listlpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='list_LPT.listlpt'),
        ),
    ]
