# Generated by Django 6.0.3 on 2026-04-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_component_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='releasedcomponent',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
