# Generated by Django 6.0.3 on 2026-04-04 17:15

import list_LPT.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPT_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.IntegerField(default=list_LPT.utils.generate_number_of_list, max_length=10, unique=True)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
