# Generated by Django 6.0.3 on 2026-04-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_LPT', '0002_order_component'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_component',
            new_name='OrderComponent',
        ),
    ]
