# Generated by Django 6.0.3 on 2026-04-04 17:24

import list_LPT.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_LPT', '0003_rename_order_component_ordercomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpt_list',
            name='list_number',
            field=models.CharField(default=list_LPT.utils.generate_number_of_list, max_length=10, unique=True),
        ),
    ]
