# Generated by Django 6.0.3 on 2026-04-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_LPT', '0004_alter_lpt_list_list_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LPT_list',
            new_name='listLPT',
        ),
    ]
