# Generated by Django 6.0.3 on 2026-04-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_LPT', '0008_ordercomponent_already_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomponent',
            name='total_boxes',
            field=models.IntegerField(default=0),
        ),
    ]
