# Generated by Django 6.0.3 on 2026-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_LPT', '0009_ordercomponent_total_boxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercomponent',
            old_name='already_released',
            new_name='already_released_quantity',
        ),
    ]
